### ISSUE TITLE
check() returns an empty data array

### ISSUE THREAD

**Issue by dotmra** [gbradley/updown#1]
Hi,

I am getting an empty data array using the `$ud->check(token)`.
Here is the output I am recieving:
```
object(GBradley\Updown\Check)#16 (4) {
  ["token":protected]=>
  string(4) "token"
  ["client":protected]=>
  object(GBradley\Updown\Client)#7 (2) {
    ["api_key":protected]=>
    string(20) "api-key"
    ["default_token":protected]=>
    NULL
  }
  ["data":protected]=>
  NULL
  ["updates":protected]=>
  array(0) {
  }
}
```

Isn't it possible to get the whole array of data instead of using `$ud->last_check_at` etc after the check?
I would like if I had access to the whole `data`-array.

Best regards,
whatTool

**Comment by gbradley** [comment]
Yes, the protected `data` variable will be `null` until the first property is accessed; basically the API call is deferred until actually needed. I can see the benefit of obtaining the entire array though, so I'll add this in shortly.
